

services:
  # Base de datos MONGODB (No MySQL)
  db_mongo:
    image: mongo:6.0
    container_name: gestor_reclamos_db
    restart: always
    ports:
      - "${DB_PORT}:27017" # Puerto por defecto de Mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_data:/data/db

  # Opcional: Interfaz gr√°fica para ver los datos
  mongo-express:
    image: mongo-express
    container_name: gestor_reclamos_gui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: db_mongo
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - db_mongo

volumes:
  mongo_data: